name: Nodejs Build Workflow

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: cd node-demo-project    
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test